import React from 'react'
import { createRoot } from 'react-dom/client'
import { FlymesPanel } from './plugin.js'
let snapshot={status:'idle',label:'REPLAY'},frames=[]
const message=document.querySelector('#message'),slider=document.querySelector('#frame'),position=document.querySelector('#position')
function selectFrame(index){const frame=frames[index];if(frame.kind==='native'){snapshot={...frame,label:'REPLAY'};position.textContent=`${index+1} / ${frames.length}`;return}snapshot=frame.decision?{...frame,label:'REPLAY'}:{status:'paused',label:'REPLAY',step:frame.step,mode:frame.mode||'REAL',decision:{...frame,action:frame.selected_action||frame.action},observation:frame.observation,dataset:frame.dataset,history:frames.slice(0,index+1)};position.textContent=`${index+1} / ${frames.length}`;document.querySelector('#evidence').textContent=`Recorded run: ${frame.run_id||'not supplied'}\nSelected action: ${snapshot.decision?.action||'not supplied'}`}
document.querySelector('#snapshot').addEventListener('change',async(event)=>{try{const text=await event.target.files[0].text();try{const parsed=JSON.parse(text);frames=parsed.kind==='native'?[parsed]:Array.isArray(parsed)?parsed:parsed.history?.length?parsed.history.map(entry=>({...parsed,...entry,simulation_time:typeof entry.decision?.simulated_ms==='number'?entry.decision.simulated_ms/1000:null,wall_time:null,health:entry.decision?.health,decision:entry.decision||{...entry,action:entry.selected_action||entry.action},history:parsed.history.filter(row=>row.step<=entry.step)})):[parsed]}catch{frames=text.trim().split(/\r?\n/).map(line=>JSON.parse(line))}if(!frames.length)throw Error('No recorded frames');slider.max=frames.length-1;slider.value=0;slider.disabled=false;selectFrame(0);message.textContent='Recorded telemetry loaded. REPLAY mode; execution controls are unavailable.'}catch(error){message.textContent=`Cannot load file: ${error.message}`}})
slider.addEventListener('input',()=>selectFrame(Number(slider.value)))
const ctx={rest:async(path,options)=>{if(path==='/native/state')return snapshot.kind==='native'?snapshot:{kind:'native',status:'disabled'};if(path==='/state')return snapshot;if(options?.body?.command==='stop')return snapshot;throw Error('Execution controls require Flymes inside Hermes Desktop. This harness only reads recorded telemetry.')}}
createRoot(document.querySelector('#root')).render(<FlymesPanel ctx={ctx}/> )
