import { createRequire } from 'node:module'
import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
const require=createRequire(process.env.FLYMES_BROWSER_MODULES ? resolve(process.env.FLYMES_BROWSER_MODULES, '../package.json') : import.meta.url)
const {chromium}=require('playwright')
const browser=await chromium.launch({headless:true,args:['--allow-file-access-from-files']})
const page=await browser.newPage({viewport:{width:1280,height:1050}})
page.on('pageerror',error=>console.error(error))
await page.goto(pathToFileURL(resolve('desktop/harness.html')).href,{waitUntil:'domcontentloaded',timeout:15000})
await page.getByRole('button',{name:'Built-in demo',exact:true}).click()
await page.waitForTimeout(1200)
await mkdir('desktop/review',{recursive:true})
await page.locator('.flymes').screenshot({path:'desktop/review/specimen-empty.png'})
await page.locator('#snapshot').setInputFiles('artifacts/replay.json')
await page.waitForTimeout(1400)
await mkdir('desktop/review',{recursive:true})
await page.locator('.flymes').screenshot({path:'desktop/review/specimen-desktop.png'})
await page.getByText('How this action was selected',{exact:true}).click()
await page.locator('.fm-neural canvas').scrollIntoViewIfNeeded()
console.log('Measured canvas',await page.locator('.fm-neural canvas').getAttribute('aria-label'))
await page.getByText('How this action was selected',{exact:true}).click()
await page.locator('.flymes').evaluate(el=>el.scrollTop=0)
console.log('Fly rendered',await page.locator('.fm-avatar-stage canvas').evaluate(el=>el.width>0))
console.log('Frames',await page.locator('#position').innerText(),'Status',await page.locator('.fm-state').innerText())
await page.locator('.flymes button').filter({hasText:'Presentation',exact:true}).click()
await page.locator('.flymes').screenshot({path:'desktop/review/specimen-presentation.png'})
await page.setViewportSize({width:420,height:1000})
await page.locator('.flymes').screenshot({path:'desktop/review/specimen-narrow.png'})
console.log('Horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))
await browser.close()
